"""Create properties table

Revision ID: cfba47ea8902
Revises: 
Create Date: 2026-04-02 23:50:13.478619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfba47ea8902'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('no_of_rooms', sa.String(length=10), nullable=False),
    sa.Column('no_of_bathrooms', sa.String(length=10), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('photo', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
